---
include:
  # Центральное устройство (пока обычный трекбол)
  - board: ergohaven
    shield: trackball
    keymap: trackball_royal
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_KEYBOARD_NAME="EH TB Royal Dongle"
      -DCONFIG_PMW3610_INVERT_X=y
      -DCONFIG_PMW3610_INVERT_Y=y
    artifact-name: trackball_royal_dongle-ergohaven-zmk

  # Периферии Imperial 44
  - board: ergohaven
    shield: imperial44_left
    keymap: imperial44_ruen
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: imperial44_left_peripheral-ergohaven-zmk

  - board: ergohaven
    shield: imperial44_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: imperial44_right_peripheral-ergohaven-zmk

  - board: ergohaven
    shield: settings_reset
