---
include:
  - board: ergohaven
    shield: imperial44_right

  - board: ergohaven
    shield: imperial44_left_qube

  - board: ergohaven
    shield: trackball_dongle
    keymap: trackball_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME=\"EH\ TB\ Dongle\"
    artifact-name: trackball_dongle_test-ergohaven-zmk

  - board: ergohaven
    shield: settings_reset

  - board: ergohaven
    shield: imperial44_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_qube_ORIGINAL_TEST-ergohaven-zmk