include:
  - board: ergohaven
    shield: imperial44_left
    keymap: imperial44_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_ruen-left
  - board: ergohaven
    shield: imperial44_right
  - board: ergohaven
    shield: settings_reset
