---
include:
  - board: ergohaven
    shield: imperial44_right

  - board: ergohaven
    shield: imperial44_left_qube

  - board: ergohaven
    shield: imperial44_qube qube dongle_screen trackball_sensor
    keymap: imperial44_trackball
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_trackball_central-ergohaven-zmk

  - board: ergohaven
    shield: settings_reset